/* Artha360 M1: local-first domain layer. CloudSyncAdapter is intentionally transport-free. */
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>crypto.randomUUID(), money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n||0));
const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const day=()=>new Date().toISOString().slice(0,10);

class ArthaDB { constructor(){this.db=null} async open(){this.db=await new Promise((ok,bad)=>{const r=indexedDB.open('artha360',1);r.onupgradeneeded=()=>{const d=r.result;[['accounts','id'],['balanceItems','id'],['transactions','id'],['events','id'],['syncQueue','id']].forEach(([n,k])=>{const s=d.createObjectStore(n,{keyPath:k});s.createIndex('updatedAt','updatedAt')});};r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)});return this} store(n,mode='readonly'){return this.db.transaction(n,mode).objectStore(n)} all(n){return new Promise((ok,bad)=>{const r=this.store(n).getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)})} put(n,v){v.updatedAt=new Date().toISOString();return new Promise((ok,bad)=>{const r=this.store(n,'readwrite').put(v);r.onsuccess=()=>ok(v);r.onerror=()=>bad(r.error)})} delete(n,id){return new Promise((ok,bad)=>{const r=this.store(n,'readwrite').delete(id);r.onsuccess=ok;r.onerror=()=>bad(r.error)})}}
class CloudSyncAdapter { async enqueue(record){return db.put('syncQueue',{id:uid(),operation:'upsert',entity:record.entity,payload:record,createdAt:new Date().toISOString()})} async pull(){return []} async push(){return {synced:0}} }
const db=new ArthaDB(), sync=new CloudSyncAdapter();
const state={accounts:[],items:[],transactions:[],events:[]};
const fields={
 account:[['name','Account name','text'],['type','Type','select:bank,credit_card,cash,loan'],['balance','Current balance','number'],['institution','Bank / issuer','text'],['lastReconciled','Statement date','date']],
 asset:[['name','Name','text'],['type','Type','select:investment,property,vehicle,insurance,cash,other_asset,loan'],['value','Current value / outstanding','number'],['notes','Notes','text']],
 transaction:[['date','Date','date'],['type','Activity','select:expense,income,transfer'],['amount','Amount','number'],['merchant','Merchant / description','text'],['accountId','Account','account'],['category','Category','text'],['note','Note','text']]
};
function now(){return new Date().toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}
async function refresh(){[state.accounts,state.items,state.transactions,state.events]=await Promise.all(['accounts','balanceItems','transactions','events'].map(n=>db.all(n)));render()}
function balanceSheet(){const cash=state.accounts.filter(a=>['bank','cash'].includes(a.type)).reduce((n,a)=>n+Number(a.balance),0)+state.items.filter(i=>i.type==='cash').reduce((n,i)=>n+Number(i.value),0);const inv=state.items.filter(i=>i.type==='investment').reduce((n,i)=>n+Number(i.value),0);const assets=cash+state.accounts.filter(a=>!['credit_card','loan'].includes(a.type)).reduce((n,a)=>n+(['bank','cash'].includes(a.type)?0:Number(a.balance)),0)+state.items.filter(i=>!['loan'].includes(i.type)).reduce((n,i)=>n+Number(i.value),0);const debt=state.accounts.filter(a=>['credit_card','loan'].includes(a.type)).reduce((n,a)=>n+Math.abs(Number(a.balance)),0)+state.items.filter(i=>i.type==='loan').reduce((n,i)=>n+Math.abs(Number(i.value)),0);return{cash,inv,assets,debt,net:assets-debt}}
function health(){let score=100, issues=[];const outdated=state.accounts.filter(a=>!a.lastReconciled||Date.now()-new Date(a.lastReconciled)>35*864e5);if(outdated.length){score-=Math.min(25,outdated.length*10);issues.push(`${outdated.length} account${outdated.length>1?'s':''} need reconciliation`)}if(!state.accounts.length) {score=0;issues.push('Add an account to establish your baseline')}const dupe=findDuplicates();if(dupe.length){score-=Math.min(15,dupe.length*5);issues.push(`${dupe.length} possible duplicate transaction${dupe.length>1?'s':''}`)}return{score:Math.max(0,score),issues}}
function findDuplicates(){const seen=new Map(),dupes=[];state.transactions.forEach(t=>{const k=[t.date,t.accountId,t.amount,(t.merchant||'').toLowerCase()].join('|');if(seen.has(k))dupes.push(t);else seen.set(k,t)});return dupes}
function render(){const b=balanceSheet(), h=health();$('#netWorth').textContent=money(b.net);$('#cashMetric').textContent=money(b.cash);$('#investmentMetric').textContent=money(b.inv);$('#debtMetric').textContent=money(b.debt);$('#healthMetric').textContent=`${h.score}/100`;$('#healthDetail').textContent=h.issues[0]||'Looking consistent';$('#netWorthChange').textContent=state.accounts.length?`Updated locally · ${now()}`:'Start by adding your first account';
 const parts=[['Cash',b.cash,''],['Other assets',Math.max(0,b.assets-b.cash-b.inv),''],['Investments',b.inv,''],['Debt',b.debt,'debt']].filter(x=>x[1]);const max=Math.max(b.assets,b.debt,1);$('#composition').innerHTML=parts.length?parts.map(([n,v,c])=>`<div class="bar-row ${c}"><span>${n}</span><div class="bar"><i style="width:${v/max*100}%"></i></div><strong>${money(v)}</strong></div>`).join(''):'<p>Add accounts, assets, or liabilities to see your picture.</p>';
 const tx=[...state.transactions].sort((a,b)=>b.date.localeCompare(a.date));const activity=t=>`<div class="activity-item"><div><strong>${esc(t.merchant||t.category||'Money movement')}</strong><small>${esc(t.date)} · ${esc(accountName(t.accountId))}</small></div><strong class="amount ${t.type}">${t.type==='expense'?'-':t.type==='income'?'+':''}${money(t.amount)}</strong></div>`;$('#recentActivity').innerHTML=tx.slice(0,5).map(activity).join('')||'No transactions yet.';renderLedger();renderAccounts();renderWealth();renderXray(b,h);renderReconciliation(h)}
function accountName(id){return state.accounts.find(a=>a.id===id)?.name||'Unassigned'}
function renderLedger(){let tx=[...state.transactions].sort((a,b)=>b.date.localeCompare(a.date)),q=$('#ledgerSearch')?.value?.toLowerCase()||'',type=$('#ledgerType')?.value||'';tx=tx.filter(t=>(!type||t.type===type)&&(!q||`${t.merchant} ${t.note} ${accountName(t.accountId)}`.toLowerCase().includes(q)));$('#ledgerList').innerHTML=tx.map(t=>`<div class="ledger-row"><div><strong>${esc(t.merchant||t.category||'Money movement')}</strong><small>${t.date} · ${esc(accountName(t.accountId))}${t.category?' · '+esc(t.category):''}</small></div><strong class="amount ${t.type}">${t.type==='expense'?'-':t.type==='income'?'+':''}${money(t.amount)}</strong></div>`).join('')||'<div class="empty-card"><p>Your universal ledger is empty.</p></div>'}
function renderAccounts(){const labels={bank:'Bank account',credit_card:'Credit card',cash:'Cash wallet',loan:'Loan account'};$('#accountList').innerHTML=state.accounts.map(a=>`<article class="card"><p class="kind">${labels[a.type]||a.type}</p><h3>${esc(a.name)}</h3><strong>${money(a.balance)}</strong><small>${esc(a.institution||'No institution')} · ${a.lastReconciled?'Reconciled '+a.lastReconciled:'Needs reconciliation'}</small></article>`).join('')||$('#emptyCard').innerHTML}
function renderWealth(){const labels={investment:'Investment',property:'Property',vehicle:'Vehicle',insurance:'Insurance',cash:'Cash',loan:'Liability',other_asset:'Other asset'};$('#wealthList').innerHTML=state.items.map(i=>`<article class="card"><p class="kind">${labels[i.type]||i.type}</p><h3>${esc(i.name)}</h3><strong>${money(i.value)}</strong><small>${esc(i.notes||'Tracked locally')}</small></article>`).join('')||$('#emptyCard').innerHTML}
function renderXray(b,h){const monthly=state.transactions.filter(t=>t.type==='expense'&&t.date.slice(0,7)===day().slice(0,7)).reduce((n,t)=>n+Number(t.amount),0);const ratio=b.assets?Math.round(b.debt/b.assets*100):0;$('#xrayContent').innerHTML=`<article><p class="eyebrow">DEBT TO ASSETS</p><strong class="${ratio>40?'warn':'good'}">${ratio}%</strong><p>${ratio>40?'Consider a payoff plan.':'Within a measured range.'}</p></article><article><p class="eyebrow">MONTHLY SPENDING</p><strong>${money(monthly)}</strong><p>Based on ledger activity this month.</p></article><article><p class="eyebrow">DATA CONFIDENCE</p><strong class="${h.score<70?'warn':'good'}">${h.score}/100</strong><p>${esc(h.issues[0]||'Records look ready for analysis.')}</p></article>`}
function renderReconciliation(h){const stale=state.accounts.filter(a=>!a.lastReconciled||Date.now()-new Date(a.lastReconciled)>35*864e5);const d=findDuplicates();$('#reconciliation').innerHTML=`<div class="notice">${h.issues.length?esc(h.issues.join(' · ')): 'No duplicate patterns found. Reconcile balances periodically for the best data health.'}</div>${[...stale,...d].map(x=>`<div class="import-row"><span>${x.merchant?`Possible duplicate: ${esc(x.merchant)} on ${x.date}`:`Reconcile ${esc(x.name)}`}</span></div>`).join('')}`}
function openForm(kind){const f=fields[kind];$('#dialogTitle').textContent=kind==='asset'?'Add asset or liability':`Add ${kind}`;$('#formFields').innerHTML=`<div class="fields">${f.map(([n,l,t])=>{let ctl;if(t.startsWith('select:'))ctl=`<select name="${n}">${t.slice(7).split(',').map(v=>`<option value="${v}">${v.replace('_',' ')}</option>`).join('')}</select>`;else if(t==='account')ctl=`<select name="accountId"><option value="">Unassigned</option>${state.accounts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select>`;else ctl=`<input required name="${n}" type="${t}" ${n==='date'||n==='lastReconciled'?`value="${day()}"`:''}>`;return `<label class="field">${l}${ctl}</label>`}).join('')}</div>`;$('#entryForm').dataset.kind=kind;$('#entryDialog').showModal()}
async function saveForm(){const kind=$('#entryForm').dataset.kind, data=Object.fromEntries(new FormData($('#entryForm')));if(kind==='account'){data.id=uid();data.balance=Number(data.balance);data.entity='accounts';await db.put('accounts',data);await sync.enqueue(data)}else if(kind==='asset'){data.id=uid();data.value=Number(data.value);data.entity='balanceItems';await db.put('balanceItems',data);await sync.enqueue(data)}else{data.id=uid();data.amount=Number(data.amount);data.entity='transactions';await db.put('transactions',data);const event={id:uid(),entity:'events',eventType:data.type,source:'manual',occurredAt:data.date,transactionId:data.id,confidence:1};await db.put('events',event);await sync.enqueue(data)}await refresh()}
function parseSms(file){const reader=new FileReader();reader.onload=()=>{const xml=new DOMParser().parseFromString(reader.result,'text/xml'),sms=[...xml.querySelectorAll('sms')],patterns=[/spent\s+(?:rs\.?|inr|₹)\s?([\d,]+).*?(?:at|on)\s+(.+)/i,/(?:debited|paid).*?(?:rs\.?|inr|₹)\s?([\d,]+).*?(?:at|to)\s+(.+)/i,/(?:credited|received).*?(?:rs\.?|inr|₹)\s?([\d,]+)/i],matches=[];sms.forEach(s=>{const text=s.getAttribute('body')||'';for(const re of patterns){const m=text.match(re);if(m){matches.push({id:uid(),date:new Date(Number(s.getAttribute('date'))).toISOString().slice(0,10),type:/credited|received/i.test(text)?'income':'expense',amount:Number(m[1].replace(/,/g,'')),merchant:(m[2]||s.getAttribute('address')||'SMS financial event').trim(),accountId:'',category:'Imported SMS',note:text,source:'sms_xml',confidence:.72});break}}});renderImport(matches,sms.length)};reader.readAsText(file)}
function renderImport(matches,total){$('#importResults').innerHTML=`<p class="notice">Scanned ${total} messages. Found ${matches.length} likely financial events. Review each before saving.</p>${matches.slice(0,30).map((t,i)=>`<div class="import-row"><span><strong>${esc(t.merchant)}</strong><br><small>${t.date} · ${money(t.amount)} · ${Math.round(t.confidence*100)}% confidence</small></span><button class="primary import-one" data-i="${i}">Add</button></div>`).join('')||''}`;$$('.import-one').forEach(b=>b.onclick=async()=>{const t=matches[Number(b.dataset.i)];t.entity='transactions';await db.put('transactions',t);await db.put('events',{id:uid(),entity:'events',eventType:t.type,source:'sms_xml',occurredAt:t.date,transactionId:t.id,confidence:t.confidence});b.textContent='Added';b.disabled=true;await refresh()})}
async function init(){await db.open();await refresh();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});$$('nav a').forEach(a=>a.onclick=()=>{const id=a.hash.slice(1);$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('nav a').forEach(x=>x.classList.toggle('active',x===a));$('#pageTitle').textContent=a.textContent;$('.sidebar').classList.remove('open')});$$('[data-open]').forEach(b=>b.onclick=()=>openForm(b.dataset.open));$('#entryForm').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();await saveForm();$('#entryDialog').close()});$('#ledgerSearch').oninput=renderLedger;$('#ledgerType').onchange=renderLedger;$('#smsFile').onchange=e=>e.target.files[0]&&parseSms(e.target.files[0]);$('#menuToggle').onclick=()=>$('.sidebar').classList.toggle('open')}
init();
