/* M2: statement importer. It deliberately never sends source files outside this browser. */
(()=>{
  let staged=[];
  const key=t=>[t.date,t.accountId,Number(t.amount).toFixed(2),(t.merchant||'').toLowerCase().replace(/[^a-z0-9]/g,'')].join('|');
  const norm=s=>(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
  const amount=v=>Number(String(v||'').replace(/[^0-9.-]/g,''))||0;
  const parseCsv=text=>{const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell.trim());cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell.trim());rows.push(row)}return rows};
  const parseDate=value=>{const v=String(value||'').trim();if(/^\d{4}-\d{1,2}-\d{1,2}/.test(v))return v.slice(0,10);const p=v.split(/[\/.-]/);if(p.length===3){let [a,b,c]=p.map(Number);if(c<100)c+=2000;if(a>12)[a,b]=[b,a];return `${c}-${String(a).padStart(2,'0')}-${String(b).padStart(2,'0')}`}const d=new Date(v);return Number.isNaN(d)?'':d.toISOString().slice(0,10)};
  const category=text=>{const s=text.toLowerCase();if(/salary|payroll|interest credit|refund/.test(s))return 'Income';if(/grocery|supermarket|mart|vegetable/.test(s))return 'Groceries';if(/uber|ola|metro|fuel|petrol/.test(s))return 'Transport';if(/restaurant|cafe|swiggy|zomato/.test(s))return 'Dining';if(/electric|water|broadband|mobile|insurance/.test(s))return 'Bills';return 'Uncategorised'};
  function accountOptions(){const select=$('#csvAccount');if(!select)return;const selected=select.value;select.innerHTML='<option value="">Choose the account this statement belongs to</option>'+state.accounts.map(a=>`<option value="${a.id}">${esc(a.name)}${a.institution?' · '+esc(a.institution):''}</option>`).join('');select.value=selected}
  function findColumn(headers,names){return headers.findIndex(h=>names.some(n=>h.includes(n)))}
  function makeTransactions(text,accountId){const rows=parseCsv(text);if(rows.length<2)throw new Error('The CSV needs a header row and at least one transaction.');const headers=rows.shift().map(norm),dateIx=findColumn(headers,['date','transactiondate','valuedate','posteddate']),descIx=findColumn(headers,['description','narration','particulars','details','merchant','transaction']),debitIx=findColumn(headers,['debit','withdrawal','dr']),creditIx=findColumn(headers,['credit','deposit','cr']),amountIx=findColumn(headers,['amount','transactionamount']);if(dateIx<0||(debitIx<0&&creditIx<0&&amountIx<0))throw new Error('Could not identify date and amount columns. Use headers such as Date, Description, Debit, Credit, or Amount.');return rows.map((r,i)=>{const debit=debitIx<0?0:amount(r[debitIx]),credit=creditIx<0?0:amount(r[creditIx]),raw=amountIx<0?0:amount(r[amountIx]),description=(r[descIx]||'Statement transaction').trim(),type=credit>0||(amountIx>=0&&raw>0)?'income':'expense',value=credit||debit||Math.abs(raw),t={id:uid(),entity:'transactions',date:parseDate(r[dateIx]),type,amount:value,merchant:description,accountId,category:category(description),note:`Imported from CSV row ${i+2}`,source:'statement_csv',confidence:.96};return t}).filter(t=>t.date&&t.amount>0)}
  function renderStage(){const box=$('#csvResults');if(!box)return;const duplicates=new Set(state.transactions.map(key));const fresh=staged.filter(t=>!duplicates.has(key(t)));box.innerHTML=staged.length?`<p class="notice">Read ${staged.length} transaction${staged.length===1?'':'s'}: ${fresh.length} ready to add, ${staged.length-fresh.length} already in this account.</p><div class="import-actions"><button class="primary" id="addCsvRows" ${fresh.length?'':'disabled'}>Add ${fresh.length} new transaction${fresh.length===1?'':'s'}</button><button class="secondary" id="clearCsvRows">Clear</button></div>${staged.slice(0,50).map(t=>`<div class="import-row ${duplicates.has(key(t))?'muted-row':''}"><span><strong>${esc(t.merchant)}</strong><br><small>${t.date} · ${esc(t.category)}${duplicates.has(key(t))?' · Possible duplicate':''}</small></span><strong class="amount ${t.type}">${t.type==='expense'?'-':'+'}${money(t.amount)}</strong></div>`).join('')}`:'';$('#addCsvRows')?.addEventListener('click',saveFresh);$('#clearCsvRows')?.addEventListener('click',()=>{staged=[];renderStage()})}
  async function saveFresh(){const existing=new Set(state.transactions.map(key)),fresh=staged.filter(t=>!existing.has(key(t)));for(const t of fresh){await db.put('transactions',t);await db.put('events',{id:uid(),entity:'events',eventType:t.type,source:'statement_csv',occurredAt:t.date,transactionId:t.id,confidence:t.confidence});await sync.enqueue(t)}staged=[];await refresh()}
  function install(){const section=$('#import'),first=$('.import-panel',section),panel=document.createElement('div');panel.className='panel import-panel';panel.innerHTML='<h3>Bank-statement CSV</h3><p>Import a bank or card statement in CSV format. Artha360 detects common date, description, debit, credit, and amount columns locally.</p><div class="import-controls"><select id="csvAccount"><option value="">Choose the account this statement belongs to</option></select><label class="file-drop compact" for="csvFile"><input id="csvFile" type="file" accept=".csv,text/csv"><span>Choose bank-statement CSV</span><small>Rows are staged and checked for duplicates before they enter your ledger</small></label></div><div id="csvResults"></div>';section.insertBefore(panel,first);accountOptions();$('#csvFile').addEventListener('change',e=>{const file=e.target.files[0],accountId=$('#csvAccount').value;if(!file||!accountId)return $('#csvResults').innerHTML='<p class="notice">Choose the matching Artha360 account before selecting a statement.</p>';const reader=new FileReader();reader.onload=()=>{try{staged=makeTransactions(reader.result,accountId);renderStage()}catch(err){$('#csvResults').innerHTML=`<p class="notice">${esc(err.message)}</p>`}};reader.readAsText(file)});const baseRender=render;render=()=>{baseRender();accountOptions();renderStage();renderCashFlow()};renderCashFlow()}
  function renderCashFlow(){const host=$('#xrayContent');if(!host)return;const month=day().slice(0,7),tx=state.transactions.filter(t=>t.date?.slice(0,7)===month),income=tx.filter(t=>t.type==='income').reduce((n,t)=>n+Number(t.amount),0),spend=tx.filter(t=>t.type==='expense').reduce((n,t)=>n+Number(t.amount),0),cats={};tx.filter(t=>t.type==='expense').forEach(t=>cats[t.category||'Uncategorised']=(cats[t.category||'Uncategorised']||0)+Number(t.amount));const top=Object.entries(cats).sort((a,b)=>b[1]-a[1])[0];const prior=$('#cashFlowInsight');if(prior)prior.remove();const card=document.createElement('article');card.id='cashFlowInsight';card.innerHTML=`<p class="eyebrow">MONTHLY CASH FLOW</p><strong class="${income-spend<0?'warn':'good'}">${income||spend?money(income-spend):'—'}</strong><p>${top?`${esc(top[0])} is your largest expense category (${money(top[1])}).`:'Import or add transactions to unlock cash-flow insights.'}</p>`;host.appendChild(card)}
  const timer=setInterval(()=>{if(typeof db!=='undefined'&&db.db){clearInterval(timer);install()}},20);
})();
